// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZcCar6uNl_x8ygTz2439WZeoJy1erLA',
    appId: '1:867737384802:web:88c992def85d194d4e9e3b',
    messagingSenderId: '867737384802',
    projectId: 'nacosvoting-ad3fb',
    authDomain: 'nacosvoting-ad3fb.firebaseapp.com',
    storageBucket: 'nacosvoting-ad3fb.firebasestorage.app',
    measurementId: 'G-1QKWWLJMKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlg_3SHoms32_0SOM5XdZOSiPxJKuCf8Q',
    appId: '1:867737384802:android:804d6e1cb9c0621f4e9e3b',
    messagingSenderId: '867737384802',
    projectId: 'nacosvoting-ad3fb',
    storageBucket: 'nacosvoting-ad3fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrhWs_wBHF7LTxNy_JxNt9hDz2_-BXGg',
    appId: '1:867737384802:ios:cf5e2fba8bc0f5b24e9e3b',
    messagingSenderId: '867737384802',
    projectId: 'nacosvoting-ad3fb',
    storageBucket: 'nacosvoting-ad3fb.firebasestorage.app',
    iosBundleId: 'com.nacos.yabatech.nacosYabatechVoting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOrhWs_wBHF7LTxNy_JxNt9hDz2_-BXGg',
    appId: '1:867737384802:ios:cf5e2fba8bc0f5b24e9e3b',
    messagingSenderId: '867737384802',
    projectId: 'nacosvoting-ad3fb',
    storageBucket: 'nacosvoting-ad3fb.firebasestorage.app',
    iosBundleId: 'com.nacos.yabatech.nacosYabatechVoting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ZcCar6uNl_x8ygTz2439WZeoJy1erLA',
    appId: '1:867737384802:web:a1621bbbe3b4a9744e9e3b',
    messagingSenderId: '867737384802',
    projectId: 'nacosvoting-ad3fb',
    authDomain: 'nacosvoting-ad3fb.firebaseapp.com',
    storageBucket: 'nacosvoting-ad3fb.firebasestorage.app',
    measurementId: 'G-9HZZZH0NHL',
  );

}