import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:nacos_yabatech_voting/auth_gate.dart';
import 'firebase_options.dart'; // Generated by 'flutterfire configure'

void main() async {
  // Ensure Flutter engine is ready before Firebase starts
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase for the specific platform (Android/Web)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const NacosVoteApp());
}

class NacosVoteApp extends StatelessWidget {
  const NacosVoteApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'NACOS Yabatech Vote',
      debugShowCheckedModeBanner: false,

      // Defining the sleek, branded UI theme
      theme: ThemeData(
        useMaterial3: true,
        primaryColor: const Color(0xFF006400), // Yabatech Green
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF006400),
          secondary: const Color(0xFFFFD700), // Yabatech Yellow
          surface: Colors.white,
        ),
        textTheme: GoogleFonts.poppinsTextTheme(), // Modern typography
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFFFFD700),
            foregroundColor: Colors.black,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
        ),
      ),

      // The AuthGate will now handle the initial routing
      home: const AuthGate(),

      // --- DEEP LINKING FIX ---
      // This tells Flutter: "If you see '/feed', load the App (AuthGate) normally."
      // This prevents the "Route Not Found" crash on the web.
      routes: {
        '/feed': (context) => const AuthGate(),
      },
    );
  }
}